# PteroServerStats Configuration File
# Need help? Join our Discord server: https://discord.znproject.my.id
version: 1 # Warning: Do not change this unless you know what you are doing!

# App Presence Configuration
presence:
  enable: true # Enable or disable app presence.
  text: "Server" # The status text shown by the app.
  type: "watching" # Available types: 'watching', 'playing', 'listening', 'competing'. (Note: 'streaming' is currently unsupported)
  status: "online" # Available types: 'online', 'idle', 'dnd', or 'invisible'

# Discord Channel and Refresh Timing Configuration
refresh: 10 # Interval in seconds for refreshing the server's stats.
timeout: 5

# Message and Embed Configuration
# To disable an option, leave the value as an empty string: ''
message:
  content: "" # Custom content for app messages. Set to '' to disable.
  attachment: "" # Attachments will delay stats refresh since they are uploaded first.

embed:
  author:
    name: "" # Author name for the panel embed.
    icon: "" # Icon URL for the author of the panel embed.
  title: "Server Stats" # Title of the panel stats embed.
  description: "Next update {{time}}" # Description for the panel. {{time}} will display the next refresh time.
  timestamp: true # Show the timestamp in the embed (true/false).
  color: "5865F2" # Embed color in hex format.
  footer:
    text: "PteroServerStats by @HirziDevs" # Footer text. Set to '' to disable.
    icon: "" # Footer icon URL.
  thumbnail: "" # Thumbnail URL for the embed.
  image: "" # Image URL for the embed.
  
# Message Button Configuration
button:
  enable: true # Enable or disable buttons in messages.
  row1:
    - label: "Panel" # Label for the first button.
      url: "https://panel.example.com" # URL for the first button.
#    - label: "Dashboard" # Remove "#" at the start of the line to use this button
#      url: "https://dash.example.com" # Remove "#" at the start of the line to use this button
#  row2: # Remove "#" at the start of the line to use this row
#    - label: "Backup Panel"
#      url: "https://panel2.example.com"
#    - label: "Backup Dashboard"
#      url: "https://dash2.example.com"

# Status Message Configuration
# For details on using custom emojis, visit: https://github.com/HirziDevs/PteroServerStats
status:
  online: ":green_circle: Online" # Status message for when a server is online.
  offline: ":red_circle: Offline" # Status message for when a server is offline.

# Server Settings
# Instructions for retrieving server IDs: https://github.com/HirziDevs/PteroServerStats
server:
  details: true # Show server details such as memory and disk usage (true/false).
  memory: true # Show server memory usage field (true/false).
  disk: true # Show server disk usage field (true/false).
  cpu: true # Show server cpu load field (true/false).
  network: true # Show server network field (true/false)
  uptime: true # Show server uptime field (true/false).

# Notifier Configuration
notifier:
  enable: false # Enable or disable notifier.
  webhook: "" # Discord Webhook URL for the notifier.
  embed:
    author:
      name: "" # Author name for the notifier embed.
      icon: "" # Icon URL for the author of the notifier embed.
    timestamp: true # Include a timestamp in the notifier embed (true/false).
    footer:
      text: "PteroServerStats Notifier" # Footer text for notifier stats.
      icon: "" # Footer icon URL.
    thumbnail: "" # Thumbnail URL for the notifier stats embed.
    image: "" # Image URL for the notifier stats embed.

# Error Logging Configuration
# Enable logging to console if servers go offline, useful for debugging.
log_error: true # Set to true to enable error logging.